<?php
/**
 * LoyaltiesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Voucherify API
 *
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 * @generated Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LoyaltiesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LoyaltiesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addMember
     *
     * Add Member.
     *
     */
    public function testAddMember()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createEarningRule
     *
     * Create Earning Rule.
     *
     */
    public function testCreateEarningRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createInBulkLoyaltyTiers
     *
     * Create loyalty tiers.
     *
     */
    public function testCreateInBulkLoyaltyTiers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createLoyaltyProgram
     *
     * Create Loyalty Campaign.
     *
     */
    public function testCreateLoyaltyProgram()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createPointsExpirationExport
     *
     * Create Points Expiration Export.
     *
     */
    public function testCreatePointsExpirationExport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createRewardAssignment1
     *
     * Create Reward Assignment.
     *
     */
    public function testCreateRewardAssignment1()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteEarningRule
     *
     * Delete Earning Rule.
     *
     */
    public function testDeleteEarningRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteLoyaltyProgram
     *
     * Delete Loyalty Campaign.
     *
     */
    public function testDeleteLoyaltyProgram()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteRewardAssignment1
     *
     * Delete Reward Assignment.
     *
     */
    public function testDeleteRewardAssignment1()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for disableEarningRule
     *
     * Disable Earning Rule.
     *
     */
    public function testDisableEarningRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for enableEarningRule
     *
     * Enable Earning Rule.
     *
     */
    public function testEnableEarningRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for exportLoyaltyCardTransactions
     *
     * Export Loyalty Card Transactions.
     *
     */
    public function testExportLoyaltyCardTransactions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for exportLoyaltyCardTransactions1
     *
     * Export Loyalty Card Transactions.
     *
     */
    public function testExportLoyaltyCardTransactions1()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEarningRule
     *
     * Get Earning Rule.
     *
     */
    public function testGetEarningRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLoyaltyProgram
     *
     * Get Loyalty Campaign.
     *
     */
    public function testGetLoyaltyProgram()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLoyaltyTier
     *
     * Get Loyalty Tier.
     *
     */
    public function testGetLoyaltyTier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMember
     *
     * Get Member.
     *
     */
    public function testGetMember()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMember1
     *
     * Get Member.
     *
     */
    public function testGetMember1()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRewardAssignment1
     *
     * Get Reward Assignment.
     *
     */
    public function testGetRewardAssignment1()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRewardAssignment2
     *
     * Get Reward Assignment.
     *
     */
    public function testGetRewardAssignment2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRewardDetails
     *
     * Get Reward Details.
     *
     */
    public function testGetRewardDetails()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listEarningRules
     *
     * List Earning Rules.
     *
     */
    public function testListEarningRules()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listLoyaltyCardTransactions
     *
     * List Loyalty Card Transactions.
     *
     */
    public function testListLoyaltyCardTransactions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listLoyaltyCardTransactions1
     *
     * List Loyalty Card Transactions.
     *
     */
    public function testListLoyaltyCardTransactions1()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listLoyaltyPrograms
     *
     * List Loyalty Campaigns.
     *
     */
    public function testListLoyaltyPrograms()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listLoyaltyTierEarningRules
     *
     * List Loyalty Tier Earning Rules.
     *
     */
    public function testListLoyaltyTierEarningRules()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listLoyaltyTierRewards
     *
     * List Loyalty Tier Rewards.
     *
     */
    public function testListLoyaltyTierRewards()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listLoyaltyTiers
     *
     * List Loyalty Tiers.
     *
     */
    public function testListLoyaltyTiers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMemberActivity
     *
     * List Member Activity.
     *
     */
    public function testListMemberActivity()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMemberActivity1
     *
     * List Member Activity.
     *
     */
    public function testListMemberActivity1()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMemberLoyaltyTier
     *
     * List Member's Loyalty Tiers.
     *
     */
    public function testListMemberLoyaltyTier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMemberRewards
     *
     * List Member Rewards.
     *
     */
    public function testListMemberRewards()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMembers
     *
     * List Members.
     *
     */
    public function testListMembers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPointsExpiration
     *
     * Get Points Expiration.
     *
     */
    public function testListPointsExpiration()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listRewardAssignments1
     *
     * List Reward Assignments.
     *
     */
    public function testListRewardAssignments1()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listRewardAssignments2
     *
     * List Reward Assignments.
     *
     */
    public function testListRewardAssignments2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for redeemReward
     *
     * Redeem Reward.
     *
     */
    public function testRedeemReward()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for redeemReward1
     *
     * Redeem Reward.
     *
     */
    public function testRedeemReward1()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transferPoints
     *
     * Transfer Loyalty Points.
     *
     */
    public function testTransferPoints()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateEarningRule
     *
     * Update Earning Rule.
     *
     */
    public function testUpdateEarningRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateLoyaltyCardBalance
     *
     * Add or Remove Loyalty Card Balance.
     *
     */
    public function testUpdateLoyaltyCardBalance()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateLoyaltyCardBalance1
     *
     * Add or Remove Loyalty Card Balance.
     *
     */
    public function testUpdateLoyaltyCardBalance1()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateLoyaltyProgram
     *
     * Update Loyalty Campaign.
     *
     */
    public function testUpdateLoyaltyProgram()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateRewardAssignment1
     *
     * Update Reward Assignment.
     *
     */
    public function testUpdateRewardAssignment1()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
