<?php
/**
 * PromotionsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Voucherify API
 *
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 * @generated Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PromotionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PromotionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addPromotionTierToCampaign
     *
     * Add Promotion Tier to Campaign.
     *
     */
    public function testAddPromotionTierToCampaign()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createPromotionStack
     *
     * Create Promotion Stack.
     *
     */
    public function testCreatePromotionStack()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletePromotionStack
     *
     * Delete Promotion Stack.
     *
     */
    public function testDeletePromotionStack()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletePromotionTier
     *
     * Delete Promotion Tier.
     *
     */
    public function testDeletePromotionTier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for disablePromotionTier
     *
     * Disable Promotion Tier.
     *
     */
    public function testDisablePromotionTier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for enablePromotionTier
     *
     * Enable Promotion Tier.
     *
     */
    public function testEnablePromotionTier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPromotionStack
     *
     * Get Promotion Stack.
     *
     */
    public function testGetPromotionStack()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPromotionTier
     *
     * Get Promotion Tier.
     *
     */
    public function testGetPromotionTier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAllPromotionStacks
     *
     * List Promotion Stacks.
     *
     */
    public function testListAllPromotionStacks()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPromotionStacksInCampaign
     *
     * List Promotion Stacks in Campaign.
     *
     */
    public function testListPromotionStacksInCampaign()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPromotionTiers
     *
     * List Promotion Tiers.
     *
     */
    public function testListPromotionTiers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPromotionTiersFromCampaign
     *
     * List Promotion Tiers from Campaign.
     *
     */
    public function testListPromotionTiersFromCampaign()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updatePromotionStack
     *
     * Update Promotion Stack.
     *
     */
    public function testUpdatePromotionStack()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updatePromotionTier
     *
     * Update Promotion Tier.
     *
     */
    public function testUpdatePromotionTier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
